---
- name: Clone K8s repository
  git:
    repo: "https://github.com/omerbenda98/puppy-adoption-k8s.git"
    dest: /home/ubuntu/puppy-adoptions-k8s
    version: main
  become_user: ubuntu

- name: Create all namespaces
  command: kubectl create namespace {{ item }}
  become_user: ubuntu
  loop:
    - argocd
    - jenkins
    - staging
    - production
  ignore_errors: yes

- name: Enable Minikube addons
  command: minikube addons enable {{ item }}
  become_user: ubuntu
  loop:
    - ingress
    - metrics-server
    - default-storageclass

- name: Apply custom ingress-nginx service configuration
  command: kubectl apply -f /home/ubuntu/puppy-adoptions-k8s/infrastructure/ingress-nginx/service.yaml -n ingress-nginx
  become_user: ubuntu
