# development/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  ports:
    - port: 3000 # Added hyphen for array item
      targetPort: 3000
  selector:
    app: frontend
