apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: puppy-adoption-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - puppy-adoption.local
      secretName: puppy-tls-secret
  rules:
    - host: puppy-adoption.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8181
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
