apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: staging
spec:
  type: NodePort
  ports:
    - port: 8181
      targetPort: 8181
      nodePort: 32224 # Using a different port than frontend
  selector:
    app: backend
