# production/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 3000 # Added hyphen for array item
      targetPort: 3000
      nodePort: 31240
  selector:
    app: frontend
