# development/frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: omerbenda98/puppy-adoption-frontend:195a0dcd3c2e6997886869789d9f9fa6f793f95e
          imagePullPolicy: Always # Added for development
          ports:
            - containerPort: 3000
          env: # Fixed env section
            - name: NODE_ENV
              value: "development"
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_URL
                  optional: true
