# development/frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: omerbenda98/puppy-adoption-frontend:37ee63743fe776ee0b80a0e8aedfd1502a227cc4
          imagePullPolicy: Always # Added for development
          ports:
            - containerPort: 3000
          env: # Fixed env section
            - name: NODE_ENV
              value: "development"
            - name: BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BACKEND_URL
                  optional: true
