# production/backend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  type: ClusterIP
  ports:
    - port: 8181
      targetPort: 8181
  selector:
    app: backend
