# production/backend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  type: NodePort # Change from NodePort to ClusterIP
  ports:
    - port: 8181
      targetPort: 8181
      nodePort: 31241
  selector:
    app: backend
